const [tool, argsJson = '{}', baseArg = 'http://127.0.0.1:4173'] = process.argv.slice(2)
if (!tool) throw new Error('Uso: node scripts/invoke_live_tool.mjs <tool> [args-json] [base-url]')
const base = baseArg.replace(/\/$/, '')
const statusResponse = await fetch(`${base}/api/live/status`, { signal: AbortSignal.timeout(5000) })
const state = await statusResponse.json()
if (!statusResponse.ok) throw new Error(state.error || `Bridge HTTP ${statusResponse.status}`)
const response = await fetch(`${base}/api/live/tools/${encodeURIComponent(tool)}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId: state.projectId, pageId: state.pageId, revision: state.revision, args: JSON.parse(argsJson) }) })
const result = await response.json()
console.log(JSON.stringify(result, null, 2))
if (!response.ok) process.exitCode = 1
