import { expect, test } from "@playwright/test";

test("un utente costruisce e configura nodi del flow senza codice", async ({ page }) => {
  const name = `Flow visuale ${Date.now()}`;
  await page.goto("/");
  await page.getByLabel("Project name").fill(name);
  await page.getByRole("button", { name: "Blank project Start with a clean canvas" }).click();
  await page.getByRole("button", { name: "Add page", exact: true }).click();
  await page.getByRole("button", { name: "Create screen" }).click();
  const palette = page.locator(".palette");
  for (const type of ["input", "button", "list"])
    await palette.locator("button").filter({ hasText: type }).click();
  await page.getByRole("button", { name: "Data", exact: true }).click();
  await page.getByRole("button", { name: "Create IndexedDB source" }).click();
  await page.getByRole("button", { name: /^Flow/ }).click();
  await page.getByRole("button", { name: "Create data flow" }).click();

  const flowNodes = page.getByRole("navigation", { name: "Flow steps" });
  await flowNodes.getByRole("button", { name: "Button click", exact: true }).click();
  await expect(page.getByLabel("Event type")).toHaveValue("click");
  await page.getByLabel("Connected element").selectOption({ label: "Button · button" });
  await expect(page.getByText("Kyro uses the same connection in preview and every export.")).toBeVisible();

  const nodePalette = page.getByRole("complementary", { name: "Add nodes to the flow" });
  const addNode = async (name: string) => {
    await nodePalette.getByLabel("Search actions").fill(name);
    await nodePalette.getByRole("button", { name, exact: true }).click();
    await nodePalette.getByLabel("Search actions").fill("");
  };
  await addNode("Load data");
  await expect(page.getByRole("complementary", { name: "Configure selected step" })).toContainText("Load data");
  await page.getByLabel("Step name").fill("Load recent tasks");
  await page.getByLabel("Connected source").selectOption({ label: "Local tasks" });
  const queryNode = page.locator(".react-flow__node").filter({ hasText: "Load recent tasks" });
  await expect(queryNode).toBeVisible();
  await flowNodes.getByRole("button", { name: "Refresh list", exact: true }).click();
  await page.getByLabel("Next step").selectOption({ label: "Load recent tasks" });
  await flowNodes.getByRole("button", { name: "Create record", exact: true }).click();
  await page.getByLabel("Pause here while debugging").check();

  await page.getByRole("button", { name: "Preview", exact: true }).click();
  const preview = page.frameLocator('iframe[title="Preview isolata"]');
  await preview.getByLabel("New task").fill("Provare il flow visuale");
  await preview.getByRole("button", { name: "Add" }).click();
  await expect(page.getByText("Paused at node")).toBeVisible();
  await expect(page.locator(".log-console")).toContainText("Not empty: completed");
  await page.locator(".log-console").screenshot({ path: "artifacts/frontend-editor-flow-breakpoint.png" });
  await page.getByRole("button", { name: "Continue execution" }).click();
  await expect(page.locator(".log-console")).toContainText("Load recent tasks: completed");
  await page.locator(".log-step").filter({ hasText: "Load recent tasks: completed" }).click();
  await expect(queryNode).toHaveClass(/selected/);
  await page.getByRole("button", { name: "From start" }).click();
  await expect(page.locator(".log-console li.current")).toContainText("Button click: completed");
  await page.getByRole("button", { name: "Next step" }).click();
  await expect(page.locator(".log-console li.current")).toContainText("Read input: completed");
  await page.getByRole("button", { name: "Replay", exact: true }).click();
  await expect(page.locator(".log-console li.current")).toContainText("Load recent tasks: completed", { timeout: 7_000 });

  await expect(page.getByText("Saved automatically")).toBeVisible();
  await page.getByRole("button", { name: "Close project and return to the dashboard" }).click();
  await page.getByRole("button", { name }).click();
  await page.getByRole("button", { name: /^Flow/ }).click();
  await page.getByRole("navigation", { name: "Flow steps" }).getByRole("button", { name: "Load recent tasks", exact: true }).click();
  await expect(page.getByLabel("Connected source")).toHaveValue(/.+/);
  await addNode("Condition");
  await page.getByLabel("Condition operator").selectOption("contains");
  await page.getByLabel("Condition value").fill("flow");
  await expect(page.getByRole("navigation", { name: "Flow steps" }).getByRole("button", { name: "Condition", exact: true })).toBeVisible();

  await addNode("Advanced function");
  await page.getByRole("button", { name: "New protected module" }).click();
  await page.getByLabel("Module operation").selectOption("uppercase");
  await page.getByLabel("Module test input").fill("canva");
  await page.getByLabel("Expected module result").fill("CANVA");
  await page.getByRole("button", { name: "Run test" }).click();
  await expect(page.getByText("Test passed: CANVA")).toBeVisible();
  await page.getByRole("button", { name: "Try now" }).click();
  await expect(page.getByText("Output: CANVA")).toBeVisible();
  await expect(page.locator(".react-flow__node").filter({ hasText: "Advanced function" })).toContainText("string → string");
  await page.screenshot({ path: "artifacts/frontend-editor-protected-module.png", fullPage: true });
  await expect(page.getByText("Saved automatically")).toBeVisible();
  await page.getByRole("button", { name: "Close project and return to the dashboard" }).click();
  await page.getByRole("button", { name }).click();
  await page.getByRole("button", { name: /^Flow/ }).click();
  await page.getByRole("navigation", { name: "Flow steps" }).getByRole("button", { name: "Advanced function", exact: true }).click();
  await expect(page.getByLabel("Connected module")).toHaveValue(/.+/);

  await page.getByRole("navigation", { name: "Flow steps" }).getByRole("button", { name: "Load recent tasks", exact: true }).click();
  await page.getByLabel("Next step").selectOption({ label: "Create record" });
  await expect(page.getByRole("alert")).toContainText("produces list");
  await page.screenshot({ path: "artifacts/frontend-editor-flow-builder.png", fullPage: true });

  await addNode("Save state");
  await page.getByLabel("State name").fill("search");
  await addNode("Format text");
  await page.getByLabel("Text format").fill("Result: {{value}}");
  await addNode("Wait");
  await page.getByLabel("Wait duration").fill("250");
  await addNode("Call API");
  await page.getByLabel("API address").fill("https://api.example.test/items");
  await page.getByLabel("API method").selectOption("POST");
  await page.getByLabel("API request body").fill('{"name":"{{value}}"}');
  await expect(page.getByText("No password is stored here")).toBeVisible();
  await addNode("Transform list");
  await page.getByLabel("Transform field").fill("name");
  await page.getByLabel("Transform format").fill("Project: {{value}}");
  await addNode("Debounce");
  await page.getByLabel("Debounce duration").fill("350");
  await addNode("Choose path");
  await page.getByLabel("Switch cases").fill("new,in progress,completed");
  const switchNode = page.locator(".react-flow__node").filter({ hasText: "Choose path" });
  await expect(switchNode.locator('[title="in progress"]')).toBeVisible();
  await addNode("Show message");
  await page.getByLabel("Step name").fill("In progress case");
  const caseEdge = page.locator(".react-flow__edge-text").filter({ hasText: "case:in progress" });
  await switchNode.click();
  await page.getByLabel("Output to connect").selectOption("case:in progress");
  await page.getByLabel("Next step").selectOption({ label: "In progress case" });
  await expect(caseEdge).toBeVisible();
  await addNode("For each item");
  await page.getByLabel("Loop limit").fill("25");
  const loopNode = page.locator(".react-flow__node").filter({ hasText: "For each item" });
  await expect(loopNode.locator('[title="Each item"]')).toBeVisible();
  await expect(loopNode.locator('[title="Done"]')).toBeVisible();
  await expect(page.getByRole("navigation", { name: "Flow steps" }).getByRole("button", { name: "Save state", exact: true })).toBeVisible();
  await expect(page.locator(".react-flow__node").filter({ hasText: "Format text" })).toContainText("unknown → string");
  await page.screenshot({ path: "artifacts/frontend-editor-flow-state.png", fullPage: true });
});
