import { expect, test } from "@playwright/test";

test("un utente costruisce e configura nodi del flow senza codice", async ({ page }) => {
  const name = `Flow visuale ${Date.now()}`;
  await page.goto("/");
  await page.getByLabel("Nome progetto").fill(name);
  await page.getByRole("button", { name: "Progetto vuoto Parti da una tela pulita" }).click();
  await page.getByRole("button", { name: "Aggiungi pagina", exact: true }).click();
  const palette = page.locator(".palette");
  for (const type of ["input", "button", "list"])
    await palette.locator("button").filter({ hasText: type }).click();
  await page.getByRole("button", { name: "Dati", exact: true }).click();
  await page.getByRole("button", { name: "Crea sorgente IndexedDB" }).click();
  await page.getByRole("button", { name: /^Flow/ }).click();
  await page.getByRole("button", { name: "Crea flow dati" }).click();

  const flowNodes = page.getByRole("navigation", { name: "Nodi del flow" });
  await flowNodes.getByRole("button", { name: "Click pulsante", exact: true }).click();
  await expect(page.getByLabel("Tipo evento")).toHaveValue("click");
  await page.getByLabel("Elemento collegato").selectOption({ label: "Button · button" });
  await expect(page.getByText("Questo collegamento viene usato uguale in preview ed export.")).toBeVisible();

  const nodePalette = page.getByRole("complementary", { name: "Aggiungi nodi al flow" });
  const addNode = async (name: string) => {
    await nodePalette.getByLabel("Cerca azione").fill(name);
    await nodePalette.getByRole("button", { name, exact: true }).click();
    await nodePalette.getByLabel("Cerca azione").fill("");
  };
  await addNode("Carica dati");
  await expect(page.getByRole("complementary", { name: "Configura nodo selezionato" })).toContainText("Carica dati");
  await page.getByLabel("Nome nodo").fill("Carica attività recenti");
  await page.getByLabel("Sorgente collegata").selectOption({ label: "Attività locali" });
  const queryNode = page.locator(".react-flow__node").filter({ hasText: "Carica attività recenti" });
  await expect(queryNode).toBeVisible();
  await flowNodes.getByRole("button", { name: "Aggiorna lista", exact: true }).click();
  await page.getByLabel("Passo successivo").selectOption({ label: "Carica attività recenti" });
  await flowNodes.getByRole("button", { name: "Inserisci record", exact: true }).click();
  await page.getByLabel("Ferma qui durante il debug").check();

  await page.getByRole("button", { name: "Preview", exact: true }).click();
  const preview = page.frameLocator('iframe[title="Preview isolata"]');
  await preview.getByLabel("Nuova attività").fill("Provare il flow visuale");
  await preview.getByRole("button", { name: "Aggiungi" }).click();
  await expect(page.getByText("In pausa sul nodo")).toBeVisible();
  await expect(page.locator(".log-console")).toContainText("Non vuoto: completato");
  await page.locator(".log-console").screenshot({ path: "artifacts/frontend-editor-flow-breakpoint.png" });
  await page.getByRole("button", { name: "Continua esecuzione" }).click();
  await expect(page.locator(".log-console")).toContainText("Carica attività recenti: completato");
  await page.locator(".log-step").filter({ hasText: "Carica attività recenti: completato" }).click();
  await expect(queryNode).toHaveClass(/selected/);
  await page.getByRole("button", { name: "Dall’inizio" }).click();
  await expect(page.locator(".log-console li.current")).toContainText("Click pulsante: completato");
  await page.getByRole("button", { name: "Passo successivo" }).click();
  await expect(page.locator(".log-console li.current")).toContainText("Leggi input: completato");
  await page.getByRole("button", { name: "Riproduci", exact: true }).click();
  await expect(page.locator(".log-console li.current")).toContainText("Carica attività recenti: completato", { timeout: 7_000 });

  await expect(page.getByText("Salvato automaticamente")).toBeVisible();
  await page.getByRole("button", { name: "Chiudi progetto e torna alla dashboard" }).click();
  await page.getByRole("button", { name }).click();
  await page.getByRole("button", { name: /^Flow/ }).click();
  await page.getByRole("navigation", { name: "Nodi del flow" }).getByRole("button", { name: "Carica attività recenti", exact: true }).click();
  await expect(page.getByLabel("Sorgente collegata")).toHaveValue(/.+/);
  await addNode("Condizione");
  await page.getByLabel("Operatore condizione").selectOption("contains");
  await page.getByLabel("Valore condizione").fill("flow");
  await expect(page.getByRole("navigation", { name: "Nodi del flow" }).getByRole("button", { name: "Condizione", exact: true })).toBeVisible();

  await addNode("Funzione avanzata");
  await page.getByRole("button", { name: "Nuovo modulo protetto" }).click();
  await page.getByLabel("Operazione modulo").selectOption("uppercase");
  await page.getByLabel("Input test modulo").fill("canva");
  await page.getByLabel("Risultato atteso modulo").fill("CANVA");
  await page.getByRole("button", { name: "Esegui test" }).click();
  await expect(page.getByText("Test superato: CANVA")).toBeVisible();
  await page.getByRole("button", { name: "Prova ora" }).click();
  await expect(page.getByText("Output: CANVA")).toBeVisible();
  await expect(page.locator(".react-flow__node").filter({ hasText: "Funzione avanzata" })).toContainText("string → string");
  await page.screenshot({ path: "artifacts/frontend-editor-protected-module.png", fullPage: true });
  await expect(page.getByText("Salvato automaticamente")).toBeVisible();
  await page.getByRole("button", { name: "Chiudi progetto e torna alla dashboard" }).click();
  await page.getByRole("button", { name }).click();
  await page.getByRole("button", { name: /^Flow/ }).click();
  await page.getByRole("navigation", { name: "Nodi del flow" }).getByRole("button", { name: "Funzione avanzata", exact: true }).click();
  await expect(page.getByLabel("Modulo collegato")).toHaveValue(/.+/);

  await page.getByRole("navigation", { name: "Nodi del flow" }).getByRole("button", { name: "Carica attività recenti", exact: true }).click();
  await page.getByLabel("Passo successivo").selectOption({ label: "Inserisci record" });
  await expect(page.getByRole("alert")).toContainText("produce list");
  await page.screenshot({ path: "artifacts/frontend-editor-flow-builder.png", fullPage: true });

  await addNode("Salva stato");
  await page.getByLabel("Nome stato").fill("ricerca");
  await addNode("Componi testo");
  await page.getByLabel("Formato testo").fill("Risultato: {{value}}");
  await addNode("Attendi");
  await page.getByLabel("Durata attesa").fill("250");
  await addNode("Chiama API");
  await page.getByLabel("Indirizzo API").fill("https://api.example.test/items");
  await page.getByLabel("Metodo API").selectOption("POST");
  await page.getByLabel("Corpo richiesta API").fill('{"name":"{{value}}"}');
  await expect(page.getByText("Nessuna password viene salvata qui")).toBeVisible();
  await addNode("Trasforma elenco");
  await page.getByLabel("Campo trasformazione").fill("name");
  await page.getByLabel("Formato trasformazione").fill("Progetto: {{value}}");
  await addNode("Limita input rapidi");
  await page.getByLabel("Durata debounce").fill("350");
  await addNode("Scegli percorso");
  await page.getByLabel("Casi scelta").fill("nuovo,in corso,completato");
  const switchNode = page.locator(".react-flow__node").filter({ hasText: "Scegli percorso" });
  await expect(switchNode.locator('[title="in corso"]')).toBeVisible();
  await addNode("Mostra notifica");
  await page.getByLabel("Nome nodo").fill("Caso in corso");
  const caseEdge = page.locator(".react-flow__edge-text").filter({ hasText: "case:in corso" });
  await switchNode.click();
  await page.getByLabel("Uscita da collegare").selectOption("case:in corso");
  await page.getByLabel("Passo successivo").selectOption({ label: "Caso in corso" });
  await expect(caseEdge).toBeVisible();
  await addNode("Per ogni elemento");
  await page.getByLabel("Limite ciclo").fill("25");
  const loopNode = page.locator(".react-flow__node").filter({ hasText: "Per ogni elemento" });
  await expect(loopNode.locator('[title="Ogni elemento"]')).toBeVisible();
  await expect(loopNode.locator('[title="Completato"]')).toBeVisible();
  await expect(page.getByRole("navigation", { name: "Nodi del flow" }).getByRole("button", { name: "Salva stato", exact: true })).toBeVisible();
  await expect(page.locator(".react-flow__node").filter({ hasText: "Componi testo" })).toContainText("unknown → string");
  await page.screenshot({ path: "artifacts/frontend-editor-flow-state.png", fullPage: true });
});
