import { expect, test } from "@playwright/test";

test("un utente chiude una modal con un nodo configurato visualmente", async ({ page }) => {
  await page.goto("/");
  await page.getByLabel("Project name").fill(`Modal visuale ${Date.now()}`);
  await page.getByRole("button", { name: "Blank project Start with a clean canvas" }).click();
  await page.getByRole("button", { name: "Add page", exact: true }).click();
  await page.getByRole("button", { name: "Create screen" }).click();
  const palette = page.locator(".palette");
  for (const type of ["input", "button", "list", "modal"]) await palette.locator("button").filter({ hasText: type }).click();
  await page.getByRole("button", { name: "Data", exact: true }).click();
  await page.getByRole("button", { name: "Create IndexedDB source" }).click();
  await page.getByRole("button", { name: /^Flow/ }).click();
  await page.getByRole("button", { name: "Create data flow" }).click();
  const nodePalette = page.getByRole("complementary", { name: "Add nodes to the flow" });
  await nodePalette.getByLabel("Search actions").fill("Manage modal");
  await nodePalette.getByRole("button", { name: "Manage modal", exact: true }).click();
  await page.getByLabel("Connected element").selectOption({ label: "Modal · modal" });
  await page.getByLabel("Dialog action").selectOption("close");
  await page.getByRole("button", { name: "Fit all" }).click();
  const eventNode = page.locator(".react-flow__node").filter({ hasText: "Button click" });
  await eventNode.locator("strong").click();
  await expect(page.getByLabel("Event type")).toBeVisible();
  await page.getByLabel("Next step").selectOption({ label: "Manage modal" });
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  const preview = page.frameLocator('iframe[title="Preview isolata"]');
  const dialog = preview.getByRole("dialog");
  await expect(dialog).toBeVisible();
  await preview.getByRole("button", { name: "Add" }).click();
  await expect(dialog).toBeHidden();
  await page.screenshot({ path: "artifacts/frontend-editor-modal-flow.png", fullPage: true });
});
