import { chromium } from '@playwright/test'

const browser = await chromium.launch({ headless: false, slowMo: 450 })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://127.0.0.1:4173')
await page.getByLabel('Nome progetto').fill(`Demo live ${new Date().toLocaleTimeString('it-IT')}`)
await page.getByRole('button', { name: 'Lista attività Vertical slice già configurato' }).click()
await page.getByRole('button', { name: 'Dati' }).click()
await page.getByRole('button', { name: 'Crea sorgente IndexedDB' }).click()
await page.getByRole('button', { name: 'Flow' }).click()
await page.getByRole('button', { name: 'Crea flow dati' }).click()
await page.waitForTimeout(1200)
await page.getByRole('button', { name: 'Preview' }).click()
const preview = page.frameLocator('iframe[title="Preview isolata"]')
await preview.getByLabel('Nuova attività').fill('Questa attività è salvata davvero')
await preview.getByRole('button', { name: 'Aggiungi' }).click()
await preview.getByText('Questa attività è salvata davvero').waitFor()
await page.waitForTimeout(1200)
await new Promise((resolve) => page.on('close', resolve))
await browser.close()
