import type { Project } from "../model";
import { generateCodeModule } from "../codeModules";
import { usesNativeRuntime } from "./nativeFiles";

export function withCodeModules(project: Project, files: Record<string, string>) {
  if (!project.codeModules.length) return files;
  for (const module of project.codeModules)
    files[`src/extensions/${moduleFile(module.id)}.ts`] = generateCodeModule(module);
  return files;
}

const moduleFile = (id: string) => `module-${id.replace(/[^a-z0-9-]/gi, "").slice(0, 36)}`;

function referencedModules(project: Project) {
  const ids = project.flows.flatMap((flow) => flow.nodes.filter((node) => node.type === "module").map((node) => node.config.moduleId));
  return project.codeModules.filter((module) => ids.includes(module.id));
}

export function moduleImports(project: Project) {
  const extensions = referencedModules(project).map((module, index) => `import { run as runExtension${index} } from './extensions/${moduleFile(module.id)}'`);
  if (usesNativeRuntime(project)) extensions.push("import { getPlatformInfo, requestNativePermission, runNativeAction } from './native'");
  return extensions.join("\n");
}

export function modulePipeline(project: Project, initial: string) {
  return referencedModules(project).reduce((value, _module, index) => `runExtension${index}(${value} as never)`, initial);
}

export function generatedFlowRuntime(project: Project) {
  const runners = referencedModules(project).map((module, index) => `${JSON.stringify(module.id)}: runExtension${index}`).join(",");
  const bindings = project.pages.flatMap((page) => page.components.flatMap((component) => Object.entries(component.events).map(([event, flowId]) => ({ componentId: component.id, event, flowId }))));
  const automatic = project.flows.flatMap((flow) => flow.nodes.filter((node) => node.type === "event" && ["pageLoad", "timer", "pageVisible", "pageHidden", "online", "offline", "deviceShake", "deepLink"].includes(node.config.trigger)).map((node) => ({ flowId: flow.id, trigger: node.config.trigger, interval: Math.min(3600000, Math.max(500, Number(node.config.interval) || 5000)), pagePath: project.pages.find((page) => page.id === node.config.pageId)?.path })));
  const nativeFallback = usesNativeRuntime(project) ? "" : `const requestNativePermission = async (_permission: string, _rationale = '') => false
const getPlatformInfo = async () => ({ platform: 'web', version: navigator.userAgent })
const runNativeAction = async (capability: string, action: string, _value: unknown, _config: Record<string, string>): Promise<never> => { throw new Error('Device action is not available: ' + capability + '.' + action) }`;
  return `type GraphNode = { id: string; type: string; label: string; position: { x: number; y: number }; config: Record<string, string> }
type GraphFlow = { id: string; name: string; nodes: GraphNode[]; edges: { id: string; source: string; target: string; path: string }[] }
const graphFlows: GraphFlow[] = ${JSON.stringify(project.flows)}
const graphState: Record<string, unknown> = ${JSON.stringify(project.state)}
const graphDebounce = new Map<string, number>()
const graphQuery = query as (sourceId?: string) => Promise<unknown[]>
const graphInsert = insert as (value: unknown, sourceId?: string) => Promise<unknown>
const graphUpdate = update as (value: unknown, sourceId?: string) => Promise<unknown>
const graphRemove = remove as (value: unknown, sourceId?: string) => Promise<unknown>
const graphRefresh = refresh as (componentId?: string) => Promise<unknown>
const extensionRunners: Record<string, (value: never) => unknown> = { ${runners} }
${nativeFallback}
const graphField = (value: unknown, key = '') => value && typeof value === 'object' ? (value as Record<string, unknown>)[key] : undefined
const graphElement = (id = '') => document.getElementById(id) ?? document.querySelector<HTMLElement>('[data-component="' + CSS.escape(id) + '"]')
const graphUiValue = (value: unknown, template = '') => template === '{{value}}' ? value : template.replaceAll('{{value}}', String(value ?? ''))
const graphRenderRecords = (element: HTMLElement, records: unknown[]) => { const list = element.querySelector('ul'); if (!list) return; list.replaceChildren(...records.map((entry) => { const item = entry && typeof entry === 'object' ? entry as Record<string, unknown> : {}, row = document.createElement('li'), title = document.createElement('strong'), description = document.createElement('p'), meta = document.createElement('div'); row.className = 'record-row'; title.textContent = String(item.text || item.title || item.name || 'Item'); description.textContent = String(item.description || ''); ['status', 'priority'].forEach((key) => { if (item[key]) { const chip = document.createElement('span'); chip.className = 'chip'; chip.textContent = String(item[key]); meta.append(chip) } }); if (item.dueDate || item.date) { const time = document.createElement('time'); time.dateTime = String(item.dueDate || item.date); time.textContent = new Date(String(item.dueDate || item.date)).toLocaleDateString('en'); meta.append(time) } row.append(title, description, meta); return row })) }
const graphListen = (element: HTMLElement | null, name: string, run: (event: Event) => void) => { if (!element) return; const native: Record<string, string> = { doubleClick: 'dblclick', pointerEnter: 'pointerenter', pointerLeave: 'pointerleave', keyDown: 'keydown' }; if (native[name]) return element.addEventListener(native[name], run); if (name === 'longPress') { let timer = 0, start: { x: number; y: number; time: number } | undefined; const cancel = () => { clearTimeout(timer); timer = 0 }; element.addEventListener('pointerdown', (event) => { start = { x: event.clientX, y: event.clientY, time: Date.now() }; timer = window.setTimeout(() => start && run(new CustomEvent('longPress', { detail: { kyroGesture: true, x: start.x, y: start.y, duration: Date.now() - start.time } })), 600) }); element.addEventListener('pointerup', cancel); element.addEventListener('pointercancel', cancel); element.addEventListener('pointerleave', cancel); return } if (name === 'swipeLeft' || name === 'swipeRight') { let start: { x: number; y: number; time: number } | undefined; element.addEventListener('pointerdown', (event) => { start = { x: event.clientX, y: event.clientY, time: Date.now() } }); element.addEventListener('pointerup', (event) => { if (!start) return; const dx = event.clientX - start.x, dy = event.clientY - start.y, duration = Math.max(1, Date.now() - start.time), matches = Math.abs(dx) > 48 && Math.abs(dx) > Math.abs(dy) && (name === 'swipeLeft' ? dx < 0 : dx > 0); if (matches) run(new CustomEvent(name, { detail: { kyroGesture: true, distanceX: dx, distanceY: dy, duration, velocity: dx / duration } })); start = undefined }); return } element.addEventListener(name, run) }
const graphMatches = (value: unknown, key = '', operator = 'equals', expected = '') => { const actual = key ? graphField(value, key) : value; if (operator === 'exists') return actual !== undefined && actual !== null && actual !== ''; if (operator === 'notEquals') return String(actual) !== expected; if (operator === 'contains') return String(actual).toLowerCase().includes(expected.toLowerCase()); if (operator === 'greater') return Number(actual) > Number(expected); if (operator === 'less') return Number(actual) < Number(expected); return String(actual) === expected }
const graphPlatformMatches = (info: { platform: string; version: string }, platform = '', minimum = '', maximum = '') => { if (platform && info.platform.toLowerCase() !== platform.toLowerCase()) return false; const current = Number.parseInt(info.version, 10), min = minimum ? Number.parseInt(minimum, 10) : undefined, max = maximum ? Number.parseInt(maximum, 10) : undefined; return !(min !== undefined && (!Number.isFinite(current) || current < min)) && !(max !== undefined && (!Number.isFinite(current) || current > max)) }
const graphNavigate = (mode = 'page', path = '/') => { if (mode === 'back') return history.back(); if (mode === 'url') { const url = new URL(path); if (!['https:', 'http:'].includes(url.protocol)) throw new Error('Usa un indirizzo HTTP o HTTPS'); return location.assign(url.toString()) } location.hash = path }
const graphRole = () => { try { const payload = authToken.split('.')[0]; return String(JSON.parse(atob(payload.replaceAll('-', '+').replaceAll('_', '/'))).role || 'viewer') } catch { return 'viewer' } }
const graphSignOut = () => { authToken = ''; localStorage.removeItem('frontend-editor-session'); location.reload() }
const graphNotify = (message: string, error = false) => { let toast = document.querySelector<HTMLElement>('[data-flow-status]'); if (!toast) { toast = document.createElement('div'); toast.dataset.flowStatus = ''; const bottom = document.querySelector('.app-bottom-nav') ? 'calc(76px + env(safe-area-inset-bottom))' : '16px'; toast.style.cssText = 'position:fixed;right:16px;bottom:' + bottom + ';z-index:9999;padding:12px 16px;border-radius:10px;background:#172033;color:white;box-shadow:0 12px 30px #0004'; document.body.append(toast) } toast.setAttribute('role', error ? 'alert' : 'status'); toast.style.background = error ? '#b42318' : '#172033'; toast.textContent = message; toast.hidden = false; window.setTimeout(() => { if (toast) toast.hidden = true }, 2600) }
const graphScheduleLocalNotification = async (title = 'Reminder', body = '', delayMs = '0') => { const delay = Math.min(604800000, Math.max(0, Number(delayMs) || 0)), native = (window as typeof window & { frontendEditorLocalNotification?: (title: string, body: string, delayMs: number) => Promise<void> }).frontendEditorLocalNotification; if (native) return native(title, body, delay); if (!('Notification' in window)) throw new Error('Notifications are not available on this device'); const permission = Notification.permission === 'default' ? await Notification.requestPermission() : Notification.permission; if (permission !== 'granted') throw new Error('Notification permission was not granted'); window.setTimeout(() => new Notification(title, { body }), delay) }
const graphPrepareFile = (value: unknown, maxMb = '2', accept = '') => new Promise<{ name: string; type: string; size: number; dataUrl: string }>((resolve, reject) => { if (!(value instanceof File)) return reject(new Error('Choose a file')); const limit = Math.min(10, Math.max(1, Number(maxMb) || 2)) * 1024 * 1024; if (value.size > limit) return reject(new Error('The file exceeds the ' + Math.round(limit / 1024 / 1024) + ' MB limit')); const allowed = accept.split(',').map((item) => item.trim().toLowerCase()).filter(Boolean); const extension = '.' + (value.name.split('.').pop() || '').toLowerCase(), mime = value.type.toLowerCase(); if (allowed.length && !allowed.some((item) => item === extension || item === mime || (item.endsWith('/*') && mime.startsWith(item.slice(0, -1))))) return reject(new Error('This file type is not allowed')); const reader = new FileReader(); reader.onerror = () => reject(new Error('The file could not be read')); reader.onload = () => resolve({ name: value.name, type: value.type, size: value.size, dataUrl: String(reader.result || '') }); reader.readAsDataURL(value) })
async function runGraph(flowId: string, input: unknown = '', ancestry: string[] = []): Promise<unknown> {
  if (ancestry.includes(flowId)) throw new Error('Reusable flow cycle: ' + [...ancestry, flowId].join(' → ')); if (ancestry.length >= 20) throw new Error('Reusable flows exceeded the maximum depth of 20')
  const flow = graphFlows.find((item) => item.id === flowId); if (!flow) throw new Error('Flow non trovato')
  const nodes = new Map(flow.nodes.map((node) => [node.id, node])); let node: GraphNode | undefined = flow.nodes.find((item) => item.type === 'event'), value = input, path = 'success', steps = 0; const visited = new Map<string, number>(), loops = new Map<string, { items: unknown[]; index: number }>()
  while (node) { if (++steps > 1000) throw new Error('Il flow ha superato il limite di 1000 passaggi'); const current: GraphNode = node, count = (visited.get(current.id) ?? 0) + 1; visited.set(current.id, count); if (count > 1 && loops.size === 0) throw new Error('Loop non controllato al nodo ' + current.label)
    try {
      if (current.type === 'readInput') value = (graphElement(current.config.componentId) as HTMLInputElement | null)?.value ?? input
      if (current.type === 'validate') { const actual = current.config.field ? graphField(value, current.config.field) : value, rule = current.config.rule || 'required', expected = current.config.value || ''; const valid = rule === 'required' ? actual !== undefined && actual !== null && String(actual).trim() !== '' : rule === 'email' ? /^\\S+@\\S+\\.\\S+$/.test(String(actual ?? '')) : rule === 'minLength' ? String(actual ?? '').length >= Math.max(0, Number(expected) || 0) : rule === 'maxLength' ? String(actual ?? '').length <= Math.max(0, Number(expected) || 0) : rule === 'min' ? Number(actual) >= Number(expected) : rule === 'max' ? Number(actual) <= Number(expected) : false; if (!valid) throw new Error(current.config.message || 'The value is not valid') }
      let condition = current.type === 'condition' ? graphMatches(value, current.config.field, current.config.operator, current.config.value) : true
      if (current.type === 'requestPermission') { const granted = await requestNativePermission(current.config.permission, current.config.rationale); value = { permission: current.config.permission, granted }; condition = granted }
      if (current.type === 'platformCondition') { const info = await getPlatformInfo(); condition = graphPlatformMatches(info, current.config.platform, current.config.minVersion, current.config.maxVersion); value = { ...info, matches: condition } }
      const switchValue = current.type === 'switch' ? String(current.config.field ? graphField(value, current.config.field) ?? '' : value ?? '') : '', switchMatch = current.type === 'switch' ? (current.config.cases || '').split(',').map((item) => item.trim()).filter(Boolean).find((item) => item === switchValue) : undefined
      let loopPath: string | undefined
      if (current.type === 'loop') { let state = loops.get(current.id); if (!state) { if (!Array.isArray(value)) throw new Error('Il ciclo richiede un elenco'); const limit = Math.min(100, Math.max(1, Number(current.config.max) || 100)); if (value.length > limit) throw new Error('Il ciclo supera il limite di ' + limit + ' elementi'); state = { items: value, index: 0 }; loops.set(current.id, state) } else state.index += 1; if (state.index < state.items.length) { value = state.items[state.index]; loopPath = 'each' } else { value = state.items; loops.delete(current.id); loopPath = 'done' } }
      if (current.type === 'getState') value = graphState[current.config.key || '']
      if (current.type === 'setState') graphState[current.config.key || ''] = value
      if (current.type === 'resetState') { delete graphState[current.config.key || '']; value = undefined }
      if (current.type === 'delay') await new Promise((resolve) => setTimeout(resolve, Math.min(10000, Math.max(0, Number(current.config.ms) || 0))))
      if (current.type === 'debounce') { const key = flow.id + ':' + current.id, version = (graphDebounce.get(key) ?? 0) + 1; graphDebounce.set(key, version); await new Promise((resolve) => setTimeout(resolve, Math.min(10000, Math.max(0, Number(current.config.ms) || 0)))); if (graphDebounce.get(key) !== version) return }
      if (current.type === 'format') value = (current.config.template || '{{value}}').replaceAll('{{value}}', String(value ?? ''))
      if (current.type === 'map') { if (!Array.isArray(value)) throw new Error('Il nodo trasformazione richiede un elenco'); value = value.map((item) => (current.config.template || '{{value}}').replaceAll('{{value}}', String(current.config.field ? graphField(item, current.config.field) ?? '' : item ?? ''))) }
      if (current.type === 'http') { const url = new URL(current.config.url); if (!['https:', 'http:'].includes(url.protocol)) throw new Error('Usa un indirizzo API HTTP o HTTPS'); const method = current.config.method || 'GET', body = ['GET', 'DELETE'].includes(method) ? undefined : (current.config.body || '{{value}}').replaceAll('{{value}}', typeof value === 'string' ? value : JSON.stringify(value)); const response = await fetch(url, { method, headers: body ? { 'content-type': 'application/json' } : undefined, body }); if (!response.ok) throw new Error('API non disponibile (' + response.status + ')'); value = response.status === 204 ? undefined : response.headers.get('content-type')?.includes('json') ? await response.json() : await response.text() }
      if (current.type === 'file') value = await graphPrepareFile(value, current.config.maxMb, current.config.accept)
      if (current.type === 'requireRole') { const role = graphRole(); let allowed; try { const parsed = JSON.parse(current.config.roles || 'admin'); allowed = Array.isArray(parsed) ? parsed.map(String) : [String(parsed)] } catch { allowed = (current.config.roles || 'admin').split(',') } allowed = allowed.map((item) => item.trim()).filter(Boolean); if (!allowed.includes(role)) throw new Error(current.config.message || 'You do not have permission for this action'); value = { role, allowed: true } }
      if (current.type === 'signOut') graphSignOut()
      if (current.type === 'insert') { const next = typeof value === 'string' ? value.trim() : value; await graphInsert(next, current.config.sourceId); value = next }
      if (current.type === 'query') { const previous = value, records = await graphQuery(current.config.sourceId); if (current.config.mode === 'one') { const configured = current.config.id || '{{value}}', id = configured === '{{value}}' ? (previous && typeof previous === 'object' ? graphField(previous, current.config.field || 'id') : previous) : configured; if (id === undefined || id === null || String(id).trim() === '') throw new Error('Indica l’ID del record da caricare'); const record = records.find((item) => String(graphField(item, 'id') ?? '') === String(id)); if (!record) throw new Error('Record ' + String(id) + ' non trovato'); value = record } else value = records }
      if (current.type === 'update') value = await graphUpdate(value, current.config.sourceId)
      if (current.type === 'delete') { await graphRemove(value, current.config.sourceId); value = undefined }
      if (current.type === 'filter') { if (!Array.isArray(value)) throw new Error('Il nodo filtro richiede un elenco'); const needle = String(current.config.stateKey ? graphState[current.config.stateKey] ?? '' : current.config.value || '').trim().toLowerCase(); if (needle && !/^all\\b/.test(needle)) value = value.filter((item) => String(graphField(item, current.config.field) ?? '').toLowerCase().includes(needle)) }
      if (current.type === 'sort') { if (!Array.isArray(value)) throw new Error('Il nodo ordinamento richiede un elenco'); value = [...value].sort((a, b) => String(graphField(a, current.config.field) ?? '').localeCompare(String(graphField(b, current.config.field) ?? '')) * (current.config.direction === 'desc' ? -1 : 1)) }
      if (current.type === 'kpi') { if (!Array.isArray(value)) throw new Error('Il nodo KPI richiede un elenco'); const values = value.map((item) => Number(graphField(item, current.config.field))).filter(Number.isFinite); value = current.config.operation === 'sum' ? values.reduce((a, b) => a + b, 0) : current.config.operation === 'average' ? (values.reduce((a, b) => a + b, 0) / (values.length || 1)) : value.length }
      if (current.type === 'module') { const runner = extensionRunners[current.config.moduleId]; if (!runner) throw new Error('Module not found'); value = runner(value as never) }
      if (current.type === 'refresh') await graphRefresh(current.config.componentId)
      if (current.type === 'navigate') graphNavigate(current.config.mode, current.config.path)
      if (current.type === 'openModal') { const element = graphElement(current.config.componentId); if (current.config.operation === 'close') element?.setAttribute('hidden', ''); else element?.removeAttribute('hidden') }
      if (current.type === 'updateUI') { const element = graphElement(current.config.componentId) as (HTMLElement & { value?: string; disabled?: boolean }) | null, operation = current.config.operation || 'show', next = graphUiValue(value, current.config.value || ''); if (!element) throw new Error('Item da cambiare non trovato'); if (operation === 'show') element.hidden = false; if (operation === 'hide') element.hidden = true; if (operation === 'enable') element.disabled = false; if (operation === 'disable') element.disabled = true; if (operation === 'focus') element.focus(); if (operation === 'text') element.textContent = String(next ?? ''); if (operation === 'value') element.value = String(next ?? ''); if (operation === 'visibleWhenZero') { const visible = Number(next) === 0; element.hidden = !visible; element.style.display = visible ? 'block' : 'none' } if (operation === 'data' && Array.isArray(next)) graphRenderRecords(element, next); if (['background', 'color', 'opacity'].includes(operation)) element.style[operation as 'background' | 'color' | 'opacity'] = String(next ?? '') }
      if (current.type === 'notify') graphNotify(current.config.message || String(value))
      if (current.type === 'localNotification') await graphScheduleLocalNotification(current.config.title, current.config.body || String(value ?? ''), current.config.delayMs)
      if (current.type === 'nativeAction') value = await runNativeAction(current.config.capability, current.config.action, value, current.config)
      if (current.type === 'runFlow') value = await runGraph(current.config.flowId, value, [...ancestry, flowId])
      if (current.type === 'log') console.debug(current.config.message || current.label, value)
      path = loopPath ?? (current.type === 'switch' ? (switchMatch ? 'case:' + switchMatch : 'error') : condition ? 'success' : 'error')
    } catch (error) { path = 'error'; graphNotify('Error: ' + (error instanceof Error ? error.message : String(error)), true); if (ancestry.length) throw error }
    const edge = flow.edges.find((item) => item.source === current.id && item.path === path); node = edge ? nodes.get(edge.target) : undefined
  }
  return value
}
${bindings.map((binding) => `{ const element = graphElement(${JSON.stringify(binding.componentId)}); const run = (event: Event) => { event.preventDefault(); const target = event.target as HTMLInputElement, gesture = (event as CustomEvent).detail?.kyroGesture ? (event as CustomEvent).detail : undefined; const input = gesture ?? (event.type === 'submit' && event.currentTarget instanceof HTMLFormElement ? Object.fromEntries(new FormData(event.currentTarget)) : target?.type === 'file' ? target.files?.[0] : target?.value ?? ''); void runGraph(${JSON.stringify(binding.flowId)}, input) }; graphListen(element, ${JSON.stringify(binding.event)}, run); ${binding.event === "submit" ? `if (element instanceof HTMLFormElement) element.querySelectorAll<HTMLButtonElement>('button[type="submit"]').forEach((button) => button.addEventListener('click', (event) => { event.preventDefault(); void runGraph(${JSON.stringify(binding.flowId)}, Object.fromEntries(new FormData(element))) }))` : ""} }`).join("\n")}
const graphPath = () => decodeURIComponent(location.hash.slice(1) || ${JSON.stringify(project.pages[0]?.path ?? "/")})
const graphPageMatches = (pagePath?: string) => !pagePath || graphPath() === pagePath
const graphRunPageLoads = () => { ${automatic.filter((item) => item.trigger === "pageLoad").map((item) => `if (graphPageMatches(${JSON.stringify(item.pagePath)})) void runGraph(${JSON.stringify(item.flowId)})`).join("; ")} }
graphRunPageLoads()
addEventListener('hashchange', graphRunPageLoads)
${automatic.filter((item) => item.trigger === "timer").map((item) => `setInterval(() => { if (graphPageMatches(${JSON.stringify(item.pagePath)})) void runGraph(${JSON.stringify(item.flowId)}) }, ${item.interval})`).join("\n")}
${automatic.filter((item) => item.trigger === "online" || item.trigger === "offline").map((item) => `addEventListener(${JSON.stringify(item.trigger)}, () => { if (graphPageMatches(${JSON.stringify(item.pagePath)})) void runGraph(${JSON.stringify(item.flowId)}) })`).join("\n")}
${automatic.filter((item) => item.trigger === "pageVisible" || item.trigger === "pageHidden").map((item) => `document.addEventListener('visibilitychange', () => { if (graphPageMatches(${JSON.stringify(item.pagePath)}) && (${JSON.stringify(item.trigger)} === 'pageVisible') === !document.hidden) void runGraph(${JSON.stringify(item.flowId)}) })`).join("\n")}
${automatic.filter((item) => item.trigger === "deepLink").map((item) => `addEventListener('kyroDeepLink', (event) => { if (graphPageMatches(${JSON.stringify(item.pagePath)})) void runGraph(${JSON.stringify(item.flowId)}, (event as CustomEvent).detail) })`).join("\n")}
${automatic.filter((item) => item.trigger === "deviceShake").map((item, index) => `{ let graphLastShake${index} = 0; addEventListener('devicemotion', (event) => { const value = event.accelerationIncludingGravity, strength = Math.abs(value?.x ?? 0) + Math.abs(value?.y ?? 0) + Math.abs(value?.z ?? 0); if (strength > 28 && Date.now() - graphLastShake${index} > 1200 && graphPageMatches(${JSON.stringify(item.pagePath)})) { graphLastShake${index} = Date.now(); void runGraph(${JSON.stringify(item.flowId)}, { x: value?.x, y: value?.y, z: value?.z }) } }) }`).join("\n")}`;
}
