import { useMemo, useState } from 'react'
import { Background, Controls, Handle, Position, ReactFlow, addEdge, type Connection, type Edge, type Node, type NodeProps, type ReactFlowInstance } from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { flowNodeTypes, type EditorComponent, type Flow, type FlowNode, type Project } from './model'
import { CodeModuleEditor } from './CodeModuleEditor'
import { actionEventCatalog, actionEvent, isComponentEvent } from './actionCatalog'
import { nativeCapabilities, nativeCapability } from './nativeCapabilities'

const colors: Record<string, string> = { event: '#7c3aed', readInput: '#2563eb', validate: '#d97706', condition: '#ea580c', switch: '#dc2626', loop: '#e11d48', getState: '#8b5cf6', setState: '#7c3aed', resetState: '#6d28d9', delay: '#f59e0b', debounce: '#f97316', format: '#a855f7', map: '#c026d3', http: '#0ea5e9', file: '#14b8a6', requireRole: '#f59e0b', signOut: '#fb7185', insert: '#059669', query: '#0f766e', update: '#15803d', delete: '#b91c1c', filter: '#9333ea', sort: '#4f46e5', kpi: '#c2410c', refresh: '#0891b2', navigate: '#0369a1', openModal: '#be185d', updateUI: '#ec4899', notify: '#db2777', localNotification: '#f97316', requestPermission: '#fb923c', nativeAction: '#22d3ee', platformCondition: '#facc15', runFlow: '#00b8c8', module: '#06b6d4', log: '#64748b' }
const labels: Record<FlowNode['type'], string> = { event: 'Event', readInput: 'Read input', validate: 'Validate', condition: 'Condition', switch: 'Choose path', loop: 'For each item', getState: 'Read state', setState: 'Save state', resetState: 'Reset state', delay: 'Wait', debounce: 'Debounce', format: 'Format text', map: 'Transform list', http: 'Call API', file: 'Prepare file', requireRole: 'Check role', signOut: 'Sign out', insert: 'Create record', query: 'Load data', update: 'Update record', delete: 'Delete record', filter: 'Filter', sort: 'Sort', kpi: 'Calculate KPI', refresh: 'Refresh UI', navigate: 'Navigate', openModal: 'Manage modal', updateUI: 'Change element', notify: 'Show message', localNotification: 'Schedule local notification', requestPermission: 'Request permission', nativeAction: 'Device action', platformCondition: 'Platform condition', runFlow: 'Run reusable flow', module: 'Advanced function', log: 'Debug' }
const defaults: Record<FlowNode['type'], Record<string, string>> = { event: { trigger: 'click', interval: '5000' }, readInput: {}, validate: { field: '', rule: 'required', value: '', message: 'This value is required' }, condition: { field: '', operator: 'equals', value: '' }, switch: { field: '', cases: 'draft,in progress,completed' }, loop: { max: '100' }, getState: { key: 'value' }, setState: { key: 'value' }, resetState: { key: 'value' }, delay: { ms: '300' }, debounce: { ms: '300' }, format: { template: '{{value}}' }, map: { field: 'text', template: '{{value}}' }, http: { url: 'https://api.example.com/items', method: 'GET', body: '{{value}}' }, file: { maxMb: '2', accept: '' }, requireRole: { roles: 'admin', previewRole: 'viewer', message: 'You do not have permission for this action' }, signOut: {}, insert: {}, query: { mode: 'all', id: '{{value}}', field: 'id' }, update: {}, delete: {}, filter: { field: 'text', value: '' }, sort: { field: 'date', direction: 'asc' }, kpi: { operation: 'count' }, refresh: {}, navigate: { mode: 'page', path: '/' }, openModal: { operation: 'open' }, updateUI: { operation: 'show', value: '' }, notify: { message: 'Action completed', level: 'success' }, localNotification: { title: 'Reminder', body: 'You have something to complete', delayMs: '2000' }, requestPermission: { permission: 'camera', rationale: 'This feature needs access to continue.' }, nativeAction: { capability: 'camera', action: 'takePhoto' }, platformCondition: { platform: 'android', minVersion: '15' }, runFlow: {}, module: {}, log: { message: 'Current value' } }
type ValueType = 'unknown' | 'string' | 'record' | 'list' | 'number' | 'writable'
const ports: Record<FlowNode['type'], { input: ValueType; output: ValueType }> = { event: { input: 'unknown', output: 'unknown' }, readInput: { input: 'unknown', output: 'string' }, validate: { input: 'unknown', output: 'unknown' }, condition: { input: 'unknown', output: 'unknown' }, switch: { input: 'unknown', output: 'unknown' }, loop: { input: 'list', output: 'unknown' }, getState: { input: 'unknown', output: 'unknown' }, setState: { input: 'unknown', output: 'unknown' }, resetState: { input: 'unknown', output: 'unknown' }, delay: { input: 'unknown', output: 'unknown' }, debounce: { input: 'unknown', output: 'unknown' }, format: { input: 'unknown', output: 'string' }, map: { input: 'list', output: 'list' }, http: { input: 'unknown', output: 'unknown' }, file: { input: 'unknown', output: 'record' }, requireRole: { input: 'unknown', output: 'record' }, signOut: { input: 'unknown', output: 'unknown' }, insert: { input: 'writable', output: 'record' }, query: { input: 'unknown', output: 'list' }, update: { input: 'record', output: 'record' }, delete: { input: 'record', output: 'unknown' }, filter: { input: 'list', output: 'list' }, sort: { input: 'list', output: 'list' }, kpi: { input: 'list', output: 'number' }, refresh: { input: 'unknown', output: 'unknown' }, navigate: { input: 'unknown', output: 'unknown' }, openModal: { input: 'unknown', output: 'unknown' }, updateUI: { input: 'unknown', output: 'unknown' }, notify: { input: 'unknown', output: 'unknown' }, localNotification: { input: 'unknown', output: 'unknown' }, requestPermission: { input: 'unknown', output: 'record' }, nativeAction: { input: 'unknown', output: 'unknown' }, platformCondition: { input: 'unknown', output: 'unknown' }, runFlow: { input: 'unknown', output: 'unknown' }, module: { input: 'unknown', output: 'unknown' }, log: { input: 'unknown', output: 'unknown' } }

const compatible = (output: ValueType, input: ValueType) => output === 'unknown' || input === 'unknown' || output === input || (input === 'writable' && ['string', 'record'].includes(output))

function FlowNode({ data }: NodeProps) {
  const value = data as { label: string; type: string; input: ValueType; output: ValueType; cases?: string[]; onSelect: () => void }
  const selectBody = (event: React.PointerEvent | React.MouseEvent) => {
    if ((event.target as HTMLElement).closest('.react-flow__handle')) return
    value.onSelect()
  }
  return <div className="flow-node" style={{ borderColor: colors[value.type] ?? '#64748b' }} onPointerDown={selectBody} onClick={selectBody}>
    {value.type !== 'event' && <Handle type="target" position={Position.Left} />}
    <small>{value.type}</small><strong>{value.label}</strong>
    {!['switch', 'loop'].includes(value.type) && <Handle type="source" position={Position.Right} id="success" />}
    {value.type === 'loop' && <Handle type="source" position={Position.Right} id="each" title="Each item" />}
    <span className="port-types">{value.input} → {value.output}</span>
    {['validate', 'condition', 'switch', 'requireRole', 'requestPermission', 'platformCondition'].includes(value.type) && <Handle type="source" position={Position.Bottom} id="error" style={value.type === 'switch' ? { left: '10%' } : undefined} />}
    {value.type === 'switch' && value.cases?.map((item, index) => <Handle key={item} type="source" position={Position.Bottom} id={`case:${item}`} title={item} style={{ left: `${25 + index * (65 / Math.max(1, value.cases!.length - 1))}%` }} />)}
    {value.type === 'loop' && <Handle type="source" position={Position.Bottom} id="done" title="Done" />}
  </div>
}

const nodeTypes = { editor: FlowNode }

export default function FlowEditor({ flow, flows, pages, components, sources, modules, roles, selectedNodeId, onChange, onModulesChange, onCreateModule, onNodeSelect }: { flow?: Flow; flows: Flow[]; pages: Project['pages']; components: EditorComponent[]; sources: Project['dataSources']; modules: Project['codeModules']; roles: string[]; selectedNodeId?: string; onChange: (flow: Flow) => void; onModulesChange: (modules: Project['codeModules']) => void; onCreateModule: (module: Project['codeModules'][number], nodeId: string) => void; onNodeSelect?: (nodeId: string) => void }) {
  const [connectionError, setConnectionError] = useState('')
  const [paletteQuery, setPaletteQuery] = useState('')
  const [connectionPath, setConnectionPath] = useState('success')
  const [flowInstance, setFlowInstance] = useState<ReactFlowInstance>()
  const portFor = (node: FlowNode) => node.type === 'query' && node.config.mode === 'one' ? { input: 'unknown' as const, output: 'record' as const } : node.type === 'nativeAction' ? { input: 'unknown' as const, output: (nativeCapability(node.config.capability)?.actions.find((action) => action.id === node.config.action)?.output ?? 'unknown') as ValueType } : node.type === 'module' ? (() => {
    const module = modules.find((item) => item.id === node.config.moduleId)
    return module ? { input: module.inputType, output: module.outputType } : ports.module
  })() : ports[node.type]
  const nodes: Node[] = useMemo(() => (flow?.nodes ?? []).map((node) => {
    const port = node.type === 'query' && node.config.mode === 'one' ? { input: 'unknown' as const, output: 'record' as const } : node.type === 'nativeAction' ? { input: 'unknown' as const, output: (nativeCapability(node.config.capability)?.actions.find((action) => action.id === node.config.action)?.output ?? 'unknown') as ValueType } : node.type === 'module' ? (() => {
      const module = modules.find((item) => item.id === node.config.moduleId)
      return module ? { input: module.inputType, output: module.outputType } : ports.module
    })() : ports[node.type]
    return { id: node.id, type: 'editor', position: node.position, selected: node.id === selectedNodeId, data: { label: node.label, type: node.type, cases: node.type === 'switch' ? node.config.cases?.split(',').map((item) => item.trim()).filter(Boolean).slice(0, 4) : undefined, onSelect: () => onNodeSelect?.(node.id), ...port } }
  }), [flow?.nodes, modules, onNodeSelect, selectedNodeId])
  const edges: Edge[] = useMemo(() => (flow?.edges ?? []).map((edge) => ({ id: edge.id, source: edge.source, target: edge.target, sourceHandle: edge.path, label: edge.path, animated: edge.path === 'success' })), [flow?.edges])
  const selected = flow?.nodes.find((node) => node.id === selectedNodeId)
  const selectedPaths = selected?.type === 'switch' ? [...(selected.config.cases ?? '').split(',').map((item) => `case:${item.trim()}`).filter((item) => item !== 'case:').slice(0, 4), 'error'] : selected?.type === 'loop' ? ['each', 'done'] : selected && ['validate', 'condition', 'requireRole', 'requestPermission', 'platformCondition'].includes(selected.type) ? ['success', 'error'] : ['success']
  const activeConnectionPath = selectedPaths.includes(connectionPath) ? connectionPath : selectedPaths[0]
  const fitAll = () => {
    if (!flowInstance || !flow?.nodes.length) return
    const left = Math.min(...flow.nodes.map((node) => node.position.x)), top = Math.min(...flow.nodes.map((node) => node.position.y))
    const right = Math.max(...flow.nodes.map((node) => node.position.x + 170)), bottom = Math.max(...flow.nodes.map((node) => node.position.y + 90))
    void flowInstance.fitBounds({ x: left, y: top, width: right - left, height: bottom - top }, { padding: 0.18, duration: 0 })
  }
  const selectFromList = (node: FlowNode) => {
    onNodeSelect?.(node.id)
    void flowInstance?.setCenter(node.position.x + 85, node.position.y + 45, { zoom: 1, duration: 0 })
  }
  const addNode = (type: FlowNode['type']) => {
    if (!flow) return
    const index = flow.nodes.length
    const node: FlowNode = { id: crypto.randomUUID(), type, label: labels[type], position: { x: 80 + (index % 4) * 190, y: 80 + Math.floor(index / 4) * 120 }, config: type === 'runFlow' ? { flowId: flows.find((item) => item.id !== flow.id)?.id ?? '' } : defaults[type] }
    onChange({ ...flow, nodes: [...flow.nodes, node] })
    onNodeSelect?.(node.id)
  }
  const updateSelected = (patch: Partial<FlowNode>) => selected && flow && onChange({ ...flow, nodes: flow.nodes.map((node) => node.id === selected.id ? { ...node, ...patch } : node) })
  const setConfig = (key: string, value: string) => selected && updateSelected({ config: { ...selected.config, [key]: value } })
  const removeSelected = () => {
    if (!selected || !flow) return
    onChange({ ...flow, nodes: flow.nodes.filter((node) => node.id !== selected.id), edges: flow.edges.filter((edge) => edge.source !== selected.id && edge.target !== selected.id) })
    onNodeSelect?.('')
  }
  const connect = (connection: Connection) => {
    if (!flow || !connection.source || !connection.target) return
    const source = flow.nodes.find((node) => node.id === connection.source), target = flow.nodes.find((node) => node.id === connection.target)
    if (!source || !target) return
    const output = portFor(source).output, input = portFor(target).input
    if (!compatible(output, input)) return setConnectionError(`Invalid connection: ${labels[source.type]} produces ${output}, but ${labels[target.type]} requires ${input === 'writable' ? 'text or a record' : input}.`)
    setConnectionError('')
    const updated = addEdge(connection, edges)
    onChange({ ...flow, edges: updated.map((edge) => ({ id: edge.id, source: edge.source, target: edge.target, path: edge.sourceHandle || 'success' })) })
  }
  const connectGuided = (path: string, targetId: string) => {
    if (!flow || !selected) return
    if (!targetId) { setConnectionError(''); return onChange({ ...flow, edges: flow.edges.filter((edge) => !(edge.source === selected.id && edge.path === path)) }) }
    const target = flow.nodes.find((node) => node.id === targetId)
    if (!target) return
    const output = portFor(selected).output, input = portFor(target).input
    if (!compatible(output, input)) return setConnectionError(`Invalid connection: ${labels[selected.type]} produces ${output}, but ${labels[target.type]} requires ${input === 'writable' ? 'text or a record' : input}.`)
    setConnectionError('')
    onChange({ ...flow, edges: [...flow.edges.filter((edge) => !(edge.source === selected.id && edge.path === path)), { id: crypto.randomUUID(), source: selected.id, target: targetId, path }] })
  }
  if (!flow) return <div className="empty-panel"><strong>No flow yet</strong><span>Choose an element and event in Design → Actions, or create a reusable flow here.</span></div>
  const matchingTypes = flowNodeTypes.filter((type) => `${labels[type]} ${type}`.toLowerCase().includes(paletteQuery.trim().toLowerCase()))
  const groups: { label: string; types: FlowNode['type'][]; open?: boolean }[] = [
    { label: 'Interactions', open: true, types: ['event', 'readInput', 'validate', 'condition', 'switch', 'delay', 'format', 'navigate', 'openModal', 'updateUI', 'notify', 'localNotification'] },
    { label: 'Device', types: ['requestPermission', 'nativeAction', 'platformCondition'] },
    { label: 'Access', types: ['requireRole', 'signOut'] },
    { label: 'Data & APIs', types: ['insert', 'query', 'update', 'delete', 'filter', 'sort', 'map', 'kpi', 'http', 'file'] },
    { label: 'Advanced', types: ['getState', 'setState', 'resetState', 'loop', 'debounce', 'refresh', 'runFlow', 'module', 'log'] },
  ]
  const nodeButtons = (types: readonly FlowNode['type'][]) => <div>{types.map((type) => <button type="button" className="secondary" key={type} onClick={() => addNode(type)}><i style={{ background: colors[type] }} />{labels[type]}</button>)}</div>
  return <div className="flow-builder">
    <aside className="flow-palette" aria-label="Add nodes to the flow">
      <strong>Add a step</strong>
      <span>Choose what happens, then connect the ports.</span>
      <details className="flow-existing-nodes" open>
        <summary>Steps in this flow <span>{flow.nodes.length}</span></summary>
        <nav aria-label="Flow steps">
          {flow.nodes.map((node) => <button type="button" key={node.id} className={node.id === selectedNodeId ? 'active' : ''} onClick={() => selectFromList(node)}>{node.label}</button>)}
        </nav>
      </details>
      <input type="search" aria-label="Search actions" placeholder="Search: notification, data, API…" value={paletteQuery} onChange={(event) => setPaletteQuery(event.target.value)} />
      {paletteQuery.trim() ? nodeButtons(matchingTypes) : <div className="flow-groups">{groups.map((group) => <details key={group.label} open={group.open}><summary>{group.label}<span>{group.types.length}</span></summary>{nodeButtons(group.types)}</details>)}</div>}
    </aside>
    <div className="flow-canvas" aria-label="Visual flow editor">
    <button type="button" className="flow-fit-button" disabled={!flowInstance} onClick={fitAll}>Fit all</button>
    <ReactFlow
      nodes={nodes}
      edges={edges}
      nodeTypes={nodeTypes}
      onNodeClick={(_, node) => onNodeSelect?.(node.id)}
      onConnect={connect}
      onNodesChange={(changes) => {
        const positions = new Map(changes.flatMap((change) => change.type === 'position' && change.position ? [[change.id, change.position] as const] : []))
        if (positions.size) onChange({ ...flow, nodes: flow.nodes.map((node) => ({ ...node, position: positions.get(node.id) ?? node.position })) })
      }}
      fitView
      onInit={setFlowInstance}
      deleteKeyCode={null}
    ><Background /><Controls onFitView={fitAll} /></ReactFlow>
    </div>
    <aside className="flow-inspector" aria-label="Configure selected step">
      {selected ? <>
        <strong>{labels[selected.type]}</strong>
        <label>Visible name<input aria-label="Step name" value={selected.label} onChange={(event) => updateSelected({ label: event.target.value })} /></label>
        <label className="switch"><input aria-label="Pause here while debugging" type="checkbox" checked={selected.config.breakpoint === 'true'} onChange={(event) => setConfig('breakpoint', String(event.target.checked))} /> Pause here while debugging</label>
        {selected.config.breakpoint === 'true' && <><label>When to pause<select aria-label="Breakpoint condition" value={selected.config.breakpointWhen ?? 'always'} onChange={(event) => setConfig('breakpointWhen', event.target.value)}><option value="always">Always</option><option value="equals">Value equals…</option><option value="contains">Value contains…</option></select></label>{selected.config.breakpointWhen && selected.config.breakpointWhen !== 'always' && <label>Value to compare<input aria-label="Breakpoint value" value={selected.config.breakpointValue ?? ''} onChange={(event) => setConfig('breakpointValue', event.target.value)} /></label>}</>}
        {selected.type === 'event' && <><label>When should it run?<select aria-label="Event type" value={selected.config.trigger ?? 'click'} onChange={(event) => setConfig('trigger', event.target.value)}>{actionEventCatalog.map((event) => <option key={event.id} value={event.id}>{event.label}</option>)}<option value="timer">At a regular interval</option></select></label>{isComponentEvent(selected.config.trigger ?? 'click') && <label>Element<select aria-label="Connected element" value={selected.config.componentId ?? ''} onChange={(event) => setConfig('componentId', event.target.value)}><option value="">Choose an element…</option>{components.map((component) => <option key={component.id} value={component.id}>{component.name} · {component.type}</option>)}</select></label>}{(actionEvent(selected.config.trigger)?.pageOnly || selected.config.trigger === 'timer') && <label>Page<select aria-label="Automatic event page" value={selected.config.pageId ?? ''} onChange={(event) => setConfig('pageId', event.target.value)}><option value="">Every page (legacy projects)</option>{pages.map((page) => <option key={page.id} value={page.id}>{page.name}</option>)}</select></label>}{selected.config.trigger === 'timer' && <label>Interval in milliseconds<input aria-label="Event interval" type="number" min="500" max="3600000" value={selected.config.interval ?? '5000'} onChange={(event) => setConfig('interval', event.target.value)} /></label>}<small>Kyro uses the same connection in preview and every export.</small></>}
        {['readInput', 'refresh', 'openModal'].includes(selected.type) && <label>Element<select aria-label="Connected element" value={selected.config.componentId ?? ''} onChange={(event) => setConfig('componentId', event.target.value)}><option value="">Choose element…</option>{components.map((component) => <option key={component.id} value={component.id}>{component.name} · {component.type}</option>)}</select></label>}
        {selected.type === 'openModal' && <label>Dialog action<select aria-label="Dialog action" value={selected.config.operation ?? 'open'} onChange={(event) => setConfig('operation', event.target.value)}><option value="open">Open</option><option value="close">Close</option></select></label>}
        {selected.type === 'updateUI' && <><label>Element to change<select aria-label="Element to change" value={selected.config.componentId ?? ''} onChange={(event) => setConfig('componentId', event.target.value)}><option value="">Choose element…</option>{components.map((component) => <option key={component.id} value={component.id}>{component.name} · {component.type}</option>)}</select></label><label>Change<select aria-label="Element change" value={selected.config.operation ?? 'show'} onChange={(event) => setConfig('operation', event.target.value)}><option value="show">Show</option><option value="hide">Hide</option><option value="enable">Enable</option><option value="disable">Disable</option><option value="text">Change text</option><option value="value">Change value</option><option value="background">Change background</option><option value="color">Change text color</option><option value="opacity">Change opacity</option></select></label>{!['show', 'hide', 'enable', 'disable'].includes(selected.config.operation ?? 'show') && <label>New value<input aria-label="Change value" value={selected.config.value ?? ''} onChange={(event) => setConfig('value', event.target.value)} /></label>}<small>This runtime change does not alter the saved design.</small></>}
        {['insert', 'query', 'update', 'delete'].includes(selected.type) && <label>Data source<select aria-label="Connected source" value={selected.config.sourceId ?? ''} onChange={(event) => setConfig('sourceId', event.target.value)}><option value="">Choose source…</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.name}</option>)}</select></label>}
        {selected.type === 'query' && <><label>What to load<select aria-label="Data load type" value={selected.config.mode ?? 'all'} onChange={(event) => setConfig('mode', event.target.value)}><option value="all">All records</option><option value="one">One record by ID</option></select></label>{selected.config.mode === 'one' && <><label>ID to find<input aria-label="Record ID to load" value={selected.config.id ?? '{{value}}'} onChange={(event) => setConfig('id', event.target.value)} /></label><label>Input field containing the ID<input aria-label="Input ID field" value={selected.config.field ?? 'id'} onChange={(event) => setConfig('field', event.target.value)} /></label><small>Use {'{{value}}'} for the previous step value; when it is a record, Kyro reads the chosen field.</small></>}</>}
        {selected.type === 'validate' && <><label>Field to validate<input aria-label="Validation field" value={selected.config.field ?? ''} placeholder="Empty = current value" onChange={(event) => setConfig('field', event.target.value)} /></label><label>Rule<select aria-label="Validation rule" value={selected.config.rule ?? 'required'} onChange={(event) => setConfig('rule', event.target.value)}><option value="required">Required</option><option value="email">Valid email</option><option value="minLength">Minimum length</option><option value="min">Minimum number</option><option value="max">Maximum number</option></select></label>{['minLength', 'min', 'max'].includes(selected.config.rule ?? 'required') && <label>Rule value<input aria-label="Validation rule value" type="number" value={selected.config.value ?? ''} onChange={(event) => setConfig('value', event.target.value)} /></label>}<label>Error message<input aria-label="Validation message" value={selected.config.message ?? ''} onChange={(event) => setConfig('message', event.target.value)} /></label></>}
        {selected.type === 'condition' && <><label>Optional field<input aria-label="Condition field" value={selected.config.field ?? ''} onChange={(event) => setConfig('field', event.target.value)} /></label><label>Comparison<select aria-label="Condition operator" value={selected.config.operator ?? 'equals'} onChange={(event) => setConfig('operator', event.target.value)}><option value="equals">Equals</option><option value="notEquals">Does not equal</option><option value="contains">Contains</option><option value="greater">Greater than</option><option value="less">Less than</option><option value="exists">Exists</option></select></label>{selected.config.operator !== 'exists' && <label>Value<input aria-label="Condition value" value={selected.config.value ?? ''} onChange={(event) => setConfig('value', event.target.value)} /></label>}</>}
        {selected.type === 'switch' && <><label>Optional field<input aria-label="Switch field" value={selected.config.field ?? ''} onChange={(event) => setConfig('field', event.target.value)} /></label><label>Comma-separated cases<input aria-label="Switch cases" value={selected.config.cases ?? ''} onChange={(event) => setConfig('cases', event.target.value)} /></label><small>Each case is an output port. The red port is the “other” path.</small></>}
        {selected.type === 'loop' && <><label>Maximum number of items<input aria-label="Loop limit" type="number" min="1" max="100" value={selected.config.max ?? '100'} onChange={(event) => setConfig('max', event.target.value)} /></label><small>Connect “Each item” to the repeated actions, then connect the last action back here. “Complete” continues after the loop.</small></>}
        {['getState', 'setState', 'resetState'].includes(selected.type) && <label>State name<input aria-label="State name" value={selected.config.key ?? ''} onChange={(event) => setConfig('key', event.target.value)} /></label>}
        {['delay', 'debounce'].includes(selected.type) && <label>{selected.type === 'debounce' ? 'Pause after the last input' : 'Wait in milliseconds'}<input aria-label={selected.type === 'debounce' ? 'Debounce duration' : 'Wait duration'} type="number" min="0" max="10000" value={selected.config.ms ?? '300'} onChange={(event) => setConfig('ms', event.target.value)} /></label>}
        {selected.type === 'format' && <label>Text template<input aria-label="Text format" value={selected.config.template ?? '{{value}}'} onChange={(event) => setConfig('template', event.target.value)} /></label>}
        {selected.type === 'map' && <><label>Field from each item<input aria-label="Transform field" value={selected.config.field ?? ''} onChange={(event) => setConfig('field', event.target.value)} /></label><label>Result template<input aria-label="Transform format" value={selected.config.template ?? '{{value}}'} onChange={(event) => setConfig('template', event.target.value)} /></label></>}
        {selected.type === 'http' && <><label>API address<input aria-label="API address" type="url" value={selected.config.url ?? ''} onChange={(event) => setConfig('url', event.target.value)} /></label><label>Operation<select aria-label="API method" value={selected.config.method ?? 'GET'} onChange={(event) => setConfig('method', event.target.value)}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select></label>{selected.config.method !== 'GET' && <label>Request body<textarea aria-label="API request body" value={selected.config.body ?? '{{value}}'} onChange={(event) => setConfig('body', event.target.value)} /></label>}<small>No password is stored here. Use an environment variable and a backend for credentials.</small></>}
        {selected.type === 'file' && <><label>Maximum size in MB<input aria-label="Maximum file size" type="number" min="1" max="10" value={selected.config.maxMb ?? '2'} onChange={(event) => setConfig('maxMb', event.target.value)} /></label><label>Accepted types<input aria-label="Accepted file types" placeholder="image/*,application/pdf" value={selected.config.accept ?? ''} onChange={(event) => setConfig('accept', event.target.value)} /></label><small>The file becomes a record with name, type, size, and content. Use a storage provider for large files.</small></>}
        {selected.type === 'requireRole' && <><label>Allowed roles<input aria-label="Allowed roles" value={selected.config.roles ?? 'admin'} placeholder="admin,editor" onChange={(event) => setConfig('roles', event.target.value)} /></label><label>Role in preview<select aria-label="Simulated preview role" value={selected.config.previewRole ?? roles[0] ?? 'viewer'} onChange={(event) => setConfig('previewRole', event.target.value)}>{[...new Set([selected.config.previewRole, ...roles, 'admin', 'editor', 'viewer'].filter(Boolean))].map((role) => <option key={role} value={role}>{role.replaceAll('-', ' ')}</option>)}</select></label><label>Message when blocked<input aria-label="Access denied message" value={selected.config.message ?? ''} onChange={(event) => setConfig('message', event.target.value)} /></label><small>Preview simulates the chosen role. In exports the role comes from the signed backend session.</small></>}
        {selected.type === 'signOut' && <small>Clears the local session and returns to the sign-in screen in the exported app.</small>}
        {selected.type === 'filter' && <><label>Field<input aria-label="Filter field" value={selected.config.field ?? ''} onChange={(event) => setConfig('field', event.target.value)} /></label><label>Value<input aria-label="Filter value" value={selected.config.value ?? ''} onChange={(event) => setConfig('value', event.target.value)} /></label></>}
        {selected.type === 'sort' && <><label>Field<input aria-label="Sort field" value={selected.config.field ?? ''} onChange={(event) => setConfig('field', event.target.value)} /></label><label>Direction<select aria-label="Sort direction" value={selected.config.direction ?? 'asc'} onChange={(event) => setConfig('direction', event.target.value)}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label></>}
        {selected.type === 'kpi' && <><label>Calculation<select aria-label="KPI calculation" value={selected.config.operation ?? 'count'} onChange={(event) => setConfig('operation', event.target.value)}><option value="count">Count records</option><option value="sum">Sum a field</option><option value="average">Average a field</option></select></label>{selected.config.operation !== 'count' && <label>Numeric field<input aria-label="KPI field" value={selected.config.field ?? ''} onChange={(event) => setConfig('field', event.target.value)} /></label>}</>}
        {selected.type === 'navigate' && <><label>Destination<select aria-label="Navigation type" value={selected.config.mode ?? 'page'} onChange={(event) => setConfig('mode', event.target.value)}><option value="page">A project page</option><option value="back">Go back</option><option value="url">An external website</option></select></label>{selected.config.mode !== 'back' && <label>{selected.config.mode === 'url' ? 'Full address' : 'Page path'}<input aria-label="Navigation path" type={selected.config.mode === 'url' ? 'url' : 'text'} value={selected.config.path ?? '/'} placeholder={selected.config.mode === 'url' ? 'https://example.com' : '/page'} onChange={(event) => setConfig('path', event.target.value)} /></label>}</>}
        {['notify', 'log'].includes(selected.type) && <label>Message<input aria-label="Node message" value={selected.config.message ?? ''} onChange={(event) => setConfig('message', event.target.value)} /></label>}
        {selected.type === 'notify' && <label>Notification type<select aria-label="Notification type" value={selected.config.level ?? 'success'} onChange={(event) => setConfig('level', event.target.value)}><option value="success">Success</option><option value="error">Error</option><option value="info">Information</option></select></label>}
        {selected.type === 'localNotification' && <><label>Title<input aria-label="Local notification title" value={selected.config.title ?? ''} onChange={(event) => setConfig('title', event.target.value)} /></label><label>Message<input aria-label="Local notification message" value={selected.config.body ?? ''} onChange={(event) => setConfig('body', event.target.value)} /></label><label>Delay in milliseconds<input aria-label="Local notification delay" type="number" min="0" max="604800000" value={selected.config.delayMs ?? '2000'} onChange={(event) => setConfig('delayMs', event.target.value)} /></label><small>Android uses a system notification; web requests browser permission.</small></>}
        {selected.type === 'requestPermission' && <><label>Permission<select aria-label="Permission to request" value={selected.config.permission ?? 'camera'} onChange={(event) => setConfig('permission', event.target.value)}>{[...new Set(nativeCapabilities.flatMap((capability) => capability.permissions))].map((permission) => <option key={permission} value={permission}>{permission}</option>)}</select></label><label>Why it is needed<textarea aria-label="Permission rationale" value={selected.config.rationale ?? ''} onChange={(event) => setConfig('rationale', event.target.value)} /></label><small>Connect Success and Denied as separate paths. Kyro adds the manifest declaration only when the graph uses it.</small></>}
        {selected.type === 'nativeAction' && <><label>Capability<select aria-label="Native capability" value={selected.config.capability ?? 'camera'} onChange={(event) => { const capability = nativeCapability(event.target.value); updateSelected({ config: { ...selected.config, capability: event.target.value, action: capability?.actions[0]?.id ?? '' } }) }}>{nativeCapabilities.map((capability) => <option key={capability.id} value={capability.id}>{capability.label}</option>)}</select></label><label>Action<select aria-label="Native action" value={selected.config.action ?? ''} onChange={(event) => setConfig('action', event.target.value)}>{nativeCapability(selected.config.capability)?.actions.map((action) => <option key={action.id} value={action.id}>{action.label}</option>)}</select></label><label>Options (advanced)<textarea aria-label="Native action options" value={selected.config.options ?? ''} placeholder="key=value, one per line" onChange={(event) => setConfig('options', event.target.value)} /></label>{nativeCapability(selected.config.capability)?.externalApproval && <small role="status">This capability uses a reviewed community extension. Kyro must show its package, permissions, and license for approval before installation.</small>}<small>{nativeCapability(selected.config.capability)?.description}</small></>}
        {selected.type === 'platformCondition' && <><label>Platform<select aria-label="Platform condition" value={selected.config.platform ?? 'android'} onChange={(event) => setConfig('platform', event.target.value)}><option value="android">Android</option><option value="ios">iOS</option><option value="web">Web</option></select></label><label>Minimum OS version<input aria-label="Minimum OS version" value={selected.config.minVersion ?? ''} placeholder="15" onChange={(event) => setConfig('minVersion', event.target.value)} /></label><label>Maximum OS version (optional)<input aria-label="Maximum OS version" value={selected.config.maxVersion ?? ''} onChange={(event) => setConfig('maxVersion', event.target.value)} /></label><small>Example: Android 15 or newer follows Success; other devices follow Does not match.</small></>}
        {selected.type === 'runFlow' && <><label>Reusable flow<select aria-label="Reusable flow" value={selected.config.flowId ?? ''} onChange={(event) => setConfig('flowId', event.target.value)}><option value="">Choose a flow…</option>{flows.filter((item) => item.id !== flow.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><small>The current value enters the selected flow and its final value continues from this node. Recursive calls are blocked.</small></>}
        {selected.type === 'module' && <><label>Module<select aria-label="Connected module" value={selected.config.moduleId ?? ''} onChange={(event) => setConfig('moduleId', event.target.value)}><option value="">Choose a module…</option>{modules.map((module) => <option key={module.id} value={module.id}>{module.name}</option>)}</select></label><button type="button" className="secondary" onClick={() => {
          const module = { id: crypto.randomUUID(), name: 'Clean text', description: '', inputType: 'string' as const, outputType: 'string' as const, operation: 'trim' as const, config: {}, tests: [{ id: crypto.randomUUID(), input: ' example ', expected: 'example' }] };
          onCreateModule(module, selected.id);
        }}>New protected module</button>{modules.find((module) => module.id === selected.config.moduleId) && <CodeModuleEditor module={modules.find((module) => module.id === selected.config.moduleId)!} onChange={(updated) => onModulesChange(modules.map((module) => module.id === updated.id ? updated : module))} />}</>}
        <fieldset><legend>Guided connection</legend>{selectedPaths.length > 1 && <label>Output to connect<select aria-label="Output to connect" value={activeConnectionPath} onChange={(event) => setConnectionPath(event.target.value)}>{selectedPaths.map((path) => <option key={path} value={path}>{path}</option>)}</select></label>}<label>Next step<select aria-label="Next step" value={flow.edges.find((edge) => edge.source === selected.id && edge.path === activeConnectionPath)?.target ?? ''} onChange={(event) => connectGuided(activeConnectionPath, event.target.value)}><option value="">None / end flow</option>{flow.nodes.filter((node) => node.id !== selected.id).map((node) => <option key={node.id} value={node.id}>{node.label}</option>)}</select></label><small>Keyboard-friendly alternative to dragging ports.</small></fieldset>
        <button type="button" className="danger" onClick={removeSelected}>Delete step</button>
      </> : <p>Select a step to configure it.</p>}
      {connectionError && <p role="alert" className="flow-connection-error">{connectionError}</p>}
    </aside>
  </div>
}
